version: '3.7'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - cassandra_network

  cassandra-reaper:
    image: thelastpickle/cassandra-reaper:latest
    container_name: cassandra-reaper
    ports:
      - "8080:8080"
    environment:
      - REAPER_STORAGE_TYPE=cassandra
      - REAPER_DATACENTER=dc1
      - REAPER_CONTACT_POINTS=cassandra
    depends_on:
      - cassandra
    networks:
      - cassandra_network

volumes:
  cassandra_data:

networks:
  cassandra_network:
    driver: bridge
