name: Publish to npm

on:
  push:
    branches:
      - main
      - master

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.services }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: filter
        run: |
          services=$(ls services)
          changed_services=()
          for service in $services; do
            if git diff --quiet HEAD^ HEAD -- services/$service; then
              continue
            fi
            changed_services+=($service)
          done
          echo "::set-output name=services::$(echo ${changed_services[@]} | jq -R -s -c 'split(" ")')"
        shell: bash

  publish:
    runs-on: ubuntu-latest
    needs: detect
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect.outputs.services) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
      - name: pwd
        run: pwd
        working-directory: services

      - name: Install dependencies
        run: npm install
        working-directory: services/${{ matrix.service }}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: services/${{ matrix.service }}
