name: Publish to npm

on:
  push:
    branches:
      - main
      - master

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.services }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - id: filter
        run: |
          echo "Listing services directory:"
          ls services || { echo "Failed to list services directory"; exit 1; }
          services=$(ls services)
          echo "Services found: $services"
          changed_services=()
          for service in $services; do
            echo "Checking service: $service"
            if git diff --quiet HEAD^ HEAD -- services/$service; then
              echo "No changes detected in $service"
            else
              echo "Changes detected in $service"
              changed_services+=($service)
            fi
          done
          if [ ${#changed_services[@]} -eq 0 ]; then
            echo "No changes detected in any service."
          else
            echo "Changed services: ${changed_services[@]}"
            echo "::set-output name=services::$(echo ${changed_services[@]} | jq -R -s -c 'split(" ")')"
          fi
        shell: bash

  publish:
    runs-on: ubuntu-latest
    needs: detect
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect.outputs.services) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm install
        working-directory: services/synthetic-metrics
